version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "misc"
    default_labels:
      - "no-release"
    automerged_updates:
      - match:
          dependency_type: "development"
          update_type: "in_range"
