name: Pull request assignee

on:
  pull_request:
    types: [assigned, unassigned]

jobs:
  assignee:
    name: 'check assignee'
    runs-on: ubuntu-18.04

    steps:
    - name: Check if there is at least one assignee
      uses: actions/github-script@0.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: pull } = await github.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
          });

          if (pull.assignees.length > 0) {
            return;
          }

          throw new Error('Should have at least one assignee');
